(source gnu)
(source marmalade)
(source melpa)

(depends-on "ansi")
(depends-on "bind-key")
(depends-on "blockdiag-mode")
(depends-on "js2-mode")
(depends-on "cask")
(depends-on "clang-format")
(depends-on "coffee-mode")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "ecukes")
(depends-on "el-mock")
(depends-on "ert-async")
(depends-on "ert-runner")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "noflet")
(depends-on "pallet")
(depends-on "php-mode")

;; 最近機械学習関連で出番が増えてるPython。
(depends-on "python-mode")

(depends-on "ruby-end")
(depends-on "ruby-mode")
(depends-on "s")
(depends-on "servant")
(depends-on "shell-split-string")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")

;; HTML/Yaml編集。設定ファイル系統はYAMLが多いのでそれなりに使います
(depends-on "web-mode")
(depends-on "yaml-mode")

(depends-on "yasnippet")

;https://github.com/qoobaa/ruby-electric
(depends-on "ruby-electric")
(depends-on "ruby-block")


;; vue
(depends-on "vue-mode")
(depends-on "vue-html-mode")
(depends-on "mmm-mode")


;; package.elでやったことがCaskに反映される（このファイル)
(depends-on "pallet")

(depends-on "mew")
(depends-on "arduino-mode")

;; なぜなかった
;;(depends-on "sql-mode")
;;(depends-on "sql-indent")

(depends-on "pug-mode")
(depends-on "gtags")

(depends-on "gradle-mode")
(depends-on "groovy-mode")
(depends-on "auto-complete")
(depends-on "rspec-mode")

;;; .emacs肥大.25年目にして初の分割
(depends-on "init-loader")

(depends-on "json-mode")
(depends-on "rjsx-mode")
(depends-on "markdown-mode")
(depends-on "vimish-fold")
(depends-on "nginx-mode")

(depends-on "prettier-js")
(depends-on "exec-path-from-shell")


;; php 関数名補完
(depends-on "cl")
(depends-on "ac-php")



;; https://github.com/codesuki/add-node-modules-path
(depends-on "add-node-modules-path")
